import { EmotionState } from './emotion';
import { PersonalityProfile } from './personality';
import { TiberiusMode } from './tiberius';

/**
 * Structured context passed to the AI model.
 * The model receives this as a JSON-serialisable prompt object —
 * it does NOT decide Tibério's identity; it responds within it.
 */
export interface AIContext {
  /** Current operating mode (drunk, philosophical, etc.) */
  mode:            TiberiusMode;
  /** Snapshot of the emotional state */
  emotion:         EmotionState;
  /** Personality profile — used in the system prompt */
  personality:     PersonalityProfile;
  /** User's message */
  userMessage:     string;
  /** Intent detected by TextAnalyzer */
  intent:          string;
  /** Relevant memory excerpt (may be empty string) */
  memoryExcerpt:   string;
  /** Recent short-term conversation snippet (may be empty string) */
  recentContext:   string;
  /** Mood description from EmotionEngine.describeMood() */
  mood:            string;
}

/** A response returned by the AI layer */
export interface AIResponse {
  text:    string;
  /** Whether the response was generated by AI (true) or came from fallback (false) */
  fromAI:  boolean;
  /** Error message if the AI call failed and we fell back */
  error?:  string;
}

/**
 * Plug-in interface for AI providers.
 * Tests inject a mock that satisfies this interface without hitting a real API.
 */
export interface AIProvider {
  generate(context: AIContext): Promise<string>;
}
